version: '3'

services:

  db:
    image: mariadb
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laraveldb

  app:
    build: .
    image: brunocascio/laravel-dev
    volumes:
      - ./app:/var/www/html/app
      - ./config:/var/www/html/config
      - ./database:/var/www/html/database
      - ./public:/var/www/html/public
      - ./resources:/var/www/html/resources
      - ./routes:/var/www/html/routes
      - ./tests:/var/www/html/tests
      - ./phpunit.xml:/var/www/html/phpunit.xml
    ports:
      - 8000:8000
    command: php artisan serve --host 0.0.0.0
    depends_on:
      - db
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:inZfyLJY7AG7gMZqHt5JgeGWnqRX2HnEie0WZ9nqV0Y=
      - APP_DEBUG=true
      - APP_LOG=single
      - APP_LOG_LEVEL=debug
      - APP_URL=http://localhost
      - DB_HOST=db
      - DB_DATABASE=laraveldb
      - DB_USERNAME=root
      - DB_PASSWORD=root

volumes:
  db: